import "dotenv/config";
import path from "node:path";

// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

function tursoUrlWithToken(url: string, token?: string) {
  if (!token) return url;
  const separator = url.includes("?") ? "&" : "?";
  return `${url}${separator}authToken=${encodeURIComponent(token)}`;
}

function normalizeLocalSqliteUrl(url: string) {
  if (!url.startsWith("file:")) return url;
  const rawPath = url.slice("file:".length);
  if (!rawPath || rawPath.startsWith("/")) return url;
  return `file:${path.resolve(process.cwd(), rawPath)}`;
}

const defaultLocalDatabaseUrl = `file:${path.resolve(process.cwd(), "prisma/dev.db")}`;

const databaseUrl =
  process.env.PROD === "true"
    ? tursoUrlWithToken(process.env.TURSO_DATABASE_URL ?? "", process.env.TURSO_AUTH_TOKEN)
    : normalizeLocalSqliteUrl(process.env.DATABASE_URL || defaultLocalDatabaseUrl);

if (process.env.PROD !== "true") {
  process.env.DATABASE_URL = databaseUrl;
}

if (process.env.PROD === "true" && !process.env.TURSO_DATABASE_URL) {
  throw new Error("Missing TURSO_DATABASE_URL while PROD=true");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
