import "dotenv/config";

// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

function tursoUrlWithToken(url: string, token?: string) {
  if (!token) return url;
  const separator = url.includes("?") ? "&" : "?";
  return `${url}${separator}authToken=${encodeURIComponent(token)}`;
}

const databaseUrl =
  process.env.PROD === "true"
    ? tursoUrlWithToken(process.env.TURSO_DATABASE_URL ?? "", process.env.TURSO_AUTH_TOKEN)
    : process.env.DATABASE_URL || "file:./prisma/dev.db";

if (process.env.PROD === "true" && !process.env.TURSO_DATABASE_URL) {
  throw new Error("Missing TURSO_DATABASE_URL while PROD=true");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
