import type { Procedure } from "./types";

/** Communications, settings, the customer portal, the AI surface, and troubleshooting. */
export const ADMIN_PROCEDURES: Procedure[] = [
  {
    id: "comms-outbox",
    module: "communications",
    question: "How do I check whether a message actually reached the customer?",
    asks: ["outbox", "did the message send", "message failed", "delivery status", "whatsapp not delivered", "check sent messages"],
    roles: ["ADMIN", "OPS", "MANAGER"],
    route: "/communications/outbox",
    steps: [
      "Open Communications then Outbox, at /communications/outbox. Settings then Notifications then Outbox reaches the same place.",
      "Each row is one attempt, with its channel, status and the time.",
      "PENDING means queued and not yet sent. SENT means the provider accepted it. FAILED means it was refused, with the reason on the row. DEAD means it was retried and given up on.",
      "Read the error on a failed row before changing anything — it usually names the cause exactly.",
      "For a message about one repair, the job's Messages tab shows the same rows filtered to that job.",
    ],
    notes: [
      "A row exists before delivery is attempted, deliberately. That is what makes a failure visible instead of silent.",
    ],
    next: ["comms-why-no-message", "comms-whatsapp-setup"],
  },
  {
    id: "comms-why-no-message",
    module: "troubleshooting",
    question: "Why did the customer not get a message?",
    asks: ["customer did not receive", "no whatsapp sent", "message not going out", "notifications not working", "client says no message"],
    roles: ["ADMIN", "OPS", "MANAGER"],
    route: "/communications/outbox",
    steps: [
      "Check the outbox first. The answer is almost always there.",
      "If there is a FAILED row, read its error. Usually it is the phone number format, WhatsApp configuration, or a template the provider has not approved.",
      "If there is no row at all, nothing was ever queued. Check that the client has a phone number, that the status actually changed, and that the notification preference or communication policy for that status is enabled.",
      "If the row is PENDING and stays that way, the retry job is not running or the attempt is scheduled for later.",
      "Confirm WhatsApp is configured for this workspace under Communications then WhatsApp.",
    ],
    notes: [
      "The two cases look identical to the customer and are completely different to fix: 'sent and failed' is a configuration problem, 'never queued' is a rules problem.",
    ],
    next: ["comms-whatsapp-setup", "comms-policies"],
  },
  {
    id: "comms-whatsapp-setup",
    module: "communications",
    question: "How do I connect WhatsApp?",
    asks: ["whatsapp setup", "connect whatsapp", "whatsapp business", "messaging provider", "configure whatsapp"],
    roles: ["ADMIN"],
    route: "/communications/whatsapp",
    steps: [
      "Open Communications then WhatsApp, at /communications/whatsapp.",
      "Enter the provider credentials for this workspace.",
      "Configuration is per workspace — each business connects its own WhatsApp account.",
      "Send a test message to confirm it works before relying on it.",
      "Message templates that the provider must approve are managed under Templates.",
    ],
    notes: [
      "Business messaging providers require pre-approved templates for messages you start. A template that has not been approved fails at send time, and the outbox will say so.",
    ],
    next: ["comms-templates", "comms-outbox"],
  },
  {
    id: "comms-templates",
    module: "communications",
    question: "How do I change the wording of automatic messages?",
    asks: ["message templates", "change message wording", "edit notification text", "customise messages"],
    roles: ["ADMIN", "OPS", "MANAGER"],
    route: "/communications/templates",
    steps: [
      "Open Communications then Templates.",
      "Edit the template for the message you want to change.",
      "Placeholders are filled in from the job or document — leave them intact or the message will read wrong.",
      "Save, then send yourself a test.",
    ],
    next: ["comms-policies"],
  },
  {
    id: "comms-policies",
    module: "communications",
    question: "How do I control which status changes message the customer?",
    asks: ["communication policy", "when customers get messaged", "stop messaging customers", "automatic notifications", "turn off messages"],
    roles: ["ADMIN", "OPS", "MANAGER"],
    route: "/communications/policies",
    steps: [
      "Open Communications then Policies.",
      "Enable a policy for each status that should message the client, and choose the template.",
      "Statuses with no policy send nothing to the client.",
      "Staff notifications are separate and live in Settings then Notifications.",
    ],
    notes: [
      "Messaging on every status change annoys customers and costs money. READY_FOR_PICKUP is the one that matters most to them.",
    ],
    next: ["comms-templates", "set-notifications"],
  },
  {
    id: "set-users",
    module: "settings",
    question: "How do I add a staff member and set what they can see?",
    asks: ["add a user", "new staff", "user roles", "permissions", "give someone access", "remove access"],
    roles: ["ADMIN"],
    route: "/settings/users",
    steps: [
      "Open Settings then Users, at /settings/users.",
      "Invite the user and set their role. The role determines what they can reach.",
      "Access mode is separate: FULL can make changes, READ_ONLY can look but not alter anything.",
      "Groups at /settings/groups grant extra permissions on top of a role.",
      "Deactivate rather than delete when someone leaves — their history stays attached to what they did.",
    ],
    notes: [
      "Give the narrowest role that lets someone do their job. Roles are enforced on the server, not by hiding menu items, so this is real security rather than tidiness.",
    ],
    next: ["set-roles-explained", "set-branches"],
  },
  {
    id: "set-roles-explained",
    module: "settings",
    question: "What can each role do?",
    asks: ["role list", "what is OPS", "difference between roles", "who can approve", "front desk permissions"],
    roles: ["ADMIN"],
    route: "/settings/users",
    steps: [
      "ADMIN — full access to the workspace, including settings and users.",
      "MANAGER and OPS — day-to-day running: jobs, clients, documents, inventory.",
      "TECH_MANAGER — the repair workshop and the technicians in it.",
      "TECHNICIAN_INTERNAL — works on jobs; sees the job detail needed to do that.",
      "TECHNICIAN_EXTERNAL — an outside contractor. Sees only assigned jobs, device details and a safe diagnosis summary. Never client contact details, pricing or payment history.",
      "FINANCE — invoices, payments, expenses, accounts and reports.",
      "SALES and its variants (SALES_MANAGER, SALES_CORPORATE, SALES_RETAIL, SALES_POS) — leads, quotations, campaigns and counter sales.",
      "TECH_FIELD — field service visits.",
      "FRONT_DESK — intake, clients and the counter.",
      "INTAKE — booking devices in, and little else.",
    ],
    notes: [
      "The external technician restriction is the one to understand properly: it is a privacy boundary enforced in the database queries themselves, so it holds even if someone reaches a page directly.",
    ],
    next: ["set-users"],
  },
  {
    id: "set-branding",
    module: "settings",
    question: "How do I put my business name and logo on documents?",
    asks: ["branding", "company logo", "letterhead", "change business name on invoice", "upload logo", "tax number on documents"],
    roles: ["ADMIN"],
    route: "/settings/branding",
    steps: [
      "Open Settings then Branding, at /settings/branding.",
      "Set the company name, address, contact details and tax number. These print on every document.",
      "Upload a logo — PNG, JPEG or WebP, up to 2 MB. SVG is refused because it can carry scripts.",
      "Save, then print one invoice to check it before sending anything to a customer.",
    ],
    notes: [
      "The logo is stored per workspace. Uploading yours does not affect any other business on the system.",
      "A new workspace starts with its own name and blank contact details rather than inheriting anyone else's. Blank prints nothing, which is honest; inherited would print another company's phone number on your invoice.",
    ],
    next: ["doc-templates"],
  },
  {
    id: "set-branches",
    module: "settings",
    question: "How do I set up branches?",
    asks: ["branches", "multiple shops", "add a branch", "second location", "multi-branch"],
    roles: ["ADMIN"],
    route: "/settings/branches",
    steps: [
      "Open Settings then Branches.",
      "Add each physical branch.",
      "Users, jobs and stock locations can be associated with a branch.",
      "Targets can be set per branch.",
    ],
    next: ["inv-locations", "sales-targets"],
  },
  {
    id: "set-notifications",
    module: "settings",
    question: "How do I control the alerts staff receive?",
    asks: ["notification preferences", "turn off alerts", "staff notifications", "bell notifications", "email alerts"],
    route: "/settings/notifications",
    steps: [
      "Open Settings then Notifications.",
      "Choose which events raise a notification and on which channel.",
      "These are staff alerts. Customer messages are controlled by communication policies, separately.",
      "In-app notifications appear in the bell menu in the header.",
    ],
    next: ["comms-policies"],
  },
  {
    id: "set-audit",
    module: "settings",
    question: "How do I see who changed something?",
    asks: ["audit log", "who did this", "history of changes", "track user actions", "accountability"],
    roles: ["ADMIN"],
    route: "/settings/audit",
    steps: [
      "Open Settings then Audit Log, at /settings/audit.",
      "Entries record who did what and when.",
      "Filter by user or date to narrow it down.",
    ],
    notes: [
      "The audit log is append-only. Entries are never deleted as a tidying-up exercise — a log that can be edited answers nothing.",
    ],
  },
  {
    id: "set-billing",
    module: "settings",
    question: "How do I see or change my subscription?",
    asks: ["billing", "subscription", "upgrade plan", "what am I paying", "change plan", "invoice for the software"],
    roles: ["ADMIN"],
    route: "/settings/billing",
    steps: [
      "Open Settings then Billing, at /settings/billing.",
      "It shows the current plan, renewal date and status.",
      "Upgrading changes what the workspace can use; the payment page handles the transaction.",
      "This is your subscription to the software — separate from the invoices you send your own customers.",
    ],
  },
  {
    id: "set-data-health",
    module: "troubleshooting",
    question: "Something looks wrong with my data — what do I check?",
    asks: ["data health", "missing records", "numbers look wrong", "data repair", "something is broken"],
    roles: ["ADMIN"],
    route: "/settings/data-heal",
    steps: [
      "Open Settings then Data Health, at /settings/data-heal.",
      "It reports inconsistencies it can detect and, where safe, offers to repair them.",
      "Read what it proposes before applying anything.",
      "If a page reports that a table is missing, that is a deployment issue rather than your data — contact support.",
    ],
    notes: [
      "Most 'wrong numbers' turn out to be a date range or a filter. Check the period first, then the branch or location filter, before assuming the data is broken.",
    ],
    next: ["fin-reports"],
  },
  {
    id: "portal-what-client-sees",
    module: "portal",
    question: "What can customers see in the portal?",
    asks: ["customer portal", "client login", "what customers can see", "self service", "track my repair"],
    route: "/portal",
    steps: [
      "Customers can check the progress of their repairs without phoning.",
      "They can see published assessments, approve or decline quotations, view their documents, and raise a complaint.",
      "They see only their own records.",
      "Assessments appear only once staff have published them; drafts are never visible.",
    ],
    next: ["portal-invite", "job-assessment-ai"],
  },
  {
    id: "portal-invite",
    module: "portal",
    question: "How do I give a customer portal access?",
    asks: ["invite customer to portal", "customer login", "portal access", "let client track repair"],
    roles: ["ADMIN", "OPS", "FRONT_DESK", "MANAGER"],
    route: "/clients",
    steps: [
      "Open the client's record from Clients.",
      "Create portal access for them.",
      "They receive the details on the contact you have recorded, so check the phone or email first.",
    ],
    next: ["client-add", "portal-what-client-sees"],
  },
  {
    id: "ai-insights-read",
    module: "ai",
    question: "How do I read the AI Insights page?",
    asks: ["ai insights", "what should I focus on", "business overview", "management dashboard", "insights page"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/ai-insights",
    steps: [
      "Open AI Insights at /ai-insights.",
      "Read the figures across the top first: cash received, cash after costs, open pipeline and low stock.",
      "'Needs your attention' lists what is genuinely stuck — overdue and stale repairs, jobs awaiting client approval, low stock, overdue invoices and supplier bills.",
      "'What to do next' turns those into actions for today.",
      "Each item points at a screen where you can act. Overdue invoices lead to the invoices list; low stock leads to inventory.",
    ],
    notes: [
      "These figures are computed from your own data with fixed rules, not estimated. They are scoped to your workspace and to the current period.",
    ],
    next: ["inv-overdue", "inv-low-stock", "ai-copilot"],
  },
  {
    id: "ai-copilot",
    module: "ai",
    question: "What can I ask the Business Copilot?",
    asks: ["business copilot", "ask the ai", "ai chat", "what can the ai do", "ai questions"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/ai-insights",
    steps: [
      "The copilot sits below the insights on /ai-insights.",
      "Ask about the state of the business: what is stuck, why cash is under pressure, which stock risks matter first.",
      "It reads aggregate figures from your workspace only — totals and counts, not individual customer records.",
      "It does not invent numbers. If something is not in the data, it will not answer it.",
    ],
    notes: [
      "It answers about your business, not about how to use the system. For 'how do I…' questions, use the AI Guide.",
    ],
    next: ["ai-guide-scope", "ai-insights-read"],
  },
  {
    id: "ai-guide-scope",
    module: "ai",
    question: "What is the AI Guide for?",
    asks: ["ai guide", "help", "how do I use this system", "tutorial", "training", "user manual"],
    steps: [
      "The AI Guide answers questions about how to use the system — the procedures in this knowledge base.",
      "Ask it in your own words: how do I invoice a repair, how do I receive stock, why did my customer not get a message.",
      "It answers from documented procedures rather than guessing, and points you at the screen you need.",
      "If it does not know something, that is a gap in the knowledge base and worth reporting — an administrator can add an article under Settings then AI Knowledge.",
    ],
    notes: [
      "Guide answers how to use the system. Copilot answers what is happening in your business. Insights shows the numbers behind the copilot.",
    ],
    next: ["ai-copilot", "ai-add-knowledge"],
  },
  {
    id: "ai-add-knowledge",
    module: "ai",
    question: "How do I add our own procedures to the AI's knowledge?",
    asks: ["add knowledge article", "teach the ai", "our own process", "custom help", "ai knowledge base"],
    roles: ["ADMIN"],
    route: "/settings/ai",
    steps: [
      "Open Settings then AI Knowledge, at /settings/ai.",
      "Add an article describing your own procedure. Scope it to this workspace so it does not affect anyone else.",
      "Write it as steps in the order a person does them, and name the screen they start from.",
      "The AI uses these articles when answering.",
      "Feedback on AI answers is collected on the same page — it shows which answers are landing and which are not.",
    ],
    notes: [
      "The knowledge base is what makes the AI useful. An article about your own workflow is worth more than any amount of general capability.",
    ],
    next: ["ai-guide-scope"],
  },
];
