import type { Procedure } from "./types";

/**
 * The document chain: quotation to invoice to receipt, plus delivery notes and
 * the two ways money goes back out (credit note and refund).
 *
 * The credit-note/refund distinction is the single most confused thing in this
 * module, so it has its own entry and both documents link to it.
 */
export const DOCUMENT_PROCEDURES: Procedure[] = [
  {
    id: "quote-create",
    module: "quotations",
    question: "How do I create a quotation?",
    asks: ["new quote", "quote a customer", "make a quotation", "estimate", "price a job for a customer"],
    roles: ["ADMIN", "OPS", "SALES", "SALES_MANAGER", "MANAGER"],
    route: "/documents/quotations",
    steps: [
      "Open Documents then Quotations, or go to /documents/quotations.",
      "Create a new quotation. From a repair, raise it against the job so the device and client carry across.",
      "Add lines — parts, labour, anything chargeable. Set the tax treatment if it applies.",
      "Set a validity date. This is what makes a quote expire rather than sit open forever.",
      "Save as a draft while you are still working on it. Send it when it is ready; the status becomes SENT.",
    ],
    notes: [
      "Quotation numbers are generated per workspace and per year. Each organisation has its own document code, so two businesses on the system never collide.",
    ],
    next: ["quote-followup", "quote-to-invoice"],
  },
  {
    id: "quote-followup",
    module: "quotations",
    question: "How do I chase a quotation the customer has not answered?",
    asks: ["follow up a quote", "chase a quotation", "customer has not replied to quote", "nudge a quote", "expire old drafts"],
    roles: ["ADMIN", "OPS", "SALES", "SALES_MANAGER"],
    route: "/documents/quotations",
    steps: [
      "Open Quotations. Quotes awaiting a reply show with status Pending.",
      "For one quote, use the row's actions menu and send a follow-up. It goes out through the outbox, so the attempt is recorded whether or not it is delivered.",
      "To chase everyone at once, use the follow-up control above the table — it acts on all quotes awaiting a reply.",
      "Old drafts that will never go anywhere can be expired in bulk from the same place, which keeps the list honest.",
    ],
    notes: [
      "Follow-ups are logged like any other outbound message. If a client says they never received one, the outbox will tell you whether it was sent, failed, or never attempted.",
    ],
    next: ["comms-outbox", "quote-to-invoice"],
  },
  {
    id: "quote-to-invoice",
    module: "quotations",
    question: "How do I turn an accepted quotation into an invoice?",
    asks: ["convert quote to invoice", "quote accepted what next", "invoice from quotation", "bill an accepted quote"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/documents/quotations",
    steps: [
      "Open Quotations and find the accepted quote.",
      "Use the row's actions menu and convert it to an invoice. The option appears for quotes that are accepted or sent.",
      "The lines, amounts, client and job link carry across, so you are not retyping anything.",
      "Check the invoice, then issue it.",
    ],
    notes: [
      "Converting does not delete the quotation. The chain stays intact, which is what lets you answer 'what did we originally quote?' six months later.",
    ],
    next: ["inv-issue", "pay-collect"],
  },
  {
    id: "inv-create-from-job",
    module: "invoices",
    question: "How do I invoice a completed repair?",
    asks: ["invoice a job", "bill a repair", "create invoice from job", "charge the customer for a repair"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/jobs/[id]",
    steps: [
      "Open the finished job.",
      "Raise an invoice from it. The client, device and agreed price carry across.",
      "Check the lines and the tax treatment, then issue.",
      "Send it to the client by WhatsApp or email, or print it at the counter.",
    ],
    next: ["pay-collect", "doc-send-whatsapp"],
  },
  {
    id: "inv-issue",
    module: "invoices",
    question: "How do I create and issue an invoice that is not tied to a repair?",
    asks: ["standalone invoice", "new invoice", "invoice without a job", "bill for a service", "sell something on invoice"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/documents/invoices",
    steps: [
      "Open Documents then Invoices, or go to /documents/invoices.",
      "Create a new invoice and pick the client, or add a new one inline.",
      "Choose the invoice type — repair, service, merchandise, contract or other. This is what makes the revenue reports readable later.",
      "Add lines, set the due date, apply tax if it applies.",
      "Issue it. A draft is not owed by anyone; an issued invoice is.",
    ],
    notes: [
      "The due date is what drives the aging buckets and the overdue reminders. An invoice with no due date will never be chased.",
    ],
    next: ["pay-collect", "inv-overdue"],
  },
  {
    id: "inv-overdue",
    module: "invoices",
    question: "How do I chase unpaid invoices?",
    asks: ["overdue invoices", "send a payment reminder", "chase money", "collections", "who owes us money", "aging"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/documents/invoices",
    steps: [
      "Open Invoices. Filter by aging — current, 1 to 30 days, 31 to 60, or 61 and over.",
      "For one invoice, open the row's actions menu and send a reminder. It goes out through the outbox.",
      "With an aging filter applied, a control above the table lets you remind everyone in that bucket at once.",
      "There is also an automatic reminder ladder in notification settings. Check whether it is enabled and not in preview mode, or it will look on while sending nothing.",
    ],
    notes: [
      "The AI Insights page counts overdue invoices and receivables at risk. This is the screen where you act on that number.",
      "A reminder that reports as sent still needs WhatsApp to be configured for the workspace. The outbox shows the real outcome.",
    ],
    next: ["comms-outbox", "pay-collect"],
  },
  {
    id: "pay-collect",
    module: "payments",
    question: "How do I record a payment from a customer?",
    asks: ["take payment", "record payment", "customer paid", "collect payment", "mark invoice paid", "part payment"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/documents/invoices",
    steps: [
      "Open the invoice.",
      "Record the payment with the amount and method.",
      "A part payment is allowed — the invoice keeps a balance and stays outstanding until it is cleared.",
      "The invoice status and totals update automatically when the balance reaches zero.",
      "Issue a receipt for what was paid.",
    ],
    notes: [
      "Record the method accurately. Cash, mobile money and bank transfer land in different places in the finance reports, and a wrong method is tedious to unpick later.",
    ],
    next: ["pay-receipt", "fin-bank"],
  },
  {
    id: "pay-receipt",
    module: "payments",
    question: "How do I issue a receipt?",
    asks: ["print a receipt", "receipt for payment", "proof of payment", "give the customer a receipt"],
    roles: ["ADMIN", "OPS", "FINANCE", "FRONT_DESK", "MANAGER"],
    route: "/documents/receipts",
    steps: [
      "A receipt follows a payment — record the payment first.",
      "Open Documents then Receipts to see them all, or issue one from the invoice you just took money against.",
      "Print it, or send it by WhatsApp or email.",
      "Receipts carry the workspace's branding and tax number from branding settings.",
    ],
    next: ["set-branding"],
  },
  {
    id: "doc-delivery-note",
    module: "documents",
    question: "What is a delivery note and when do I raise one?",
    asks: ["delivery note", "proof of delivery", "handover document", "goods delivered"],
    roles: ["ADMIN", "OPS", "FINANCE", "MANAGER"],
    route: "/documents/delivery-notes",
    steps: [
      "A delivery note records that goods or a repaired device physically left your premises and who received them.",
      "Raise it against the invoice or job it relates to.",
      "Print it for the client to sign on handover.",
    ],
    notes: [
      "A delivery note is not a bill and moves no money. It answers 'did they actually get it', which matters when a client says they did not.",
    ],
  },
  {
    id: "doc-credit-vs-refund",
    module: "documents",
    question: "What is the difference between a credit note and a refund?",
    asks: ["credit note or refund", "difference between credit note and refund", "when to use a credit note", "money back to customer", "cancel an invoice", "overcharged a customer"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/documents/credit-notes",
    steps: [
      "A credit note cancels or reduces something you have billed. No cash moves. Use it when an invoice was wrong, work was not done, or you are writing an amount off.",
      "A refund is cash actually going back to the customer. Use it when they have paid and you are returning money.",
      "The test: has the customer's money reached you yet? If not, credit note. If yes and it is going back, refund.",
      "Both are raised from Documents — Credit Notes at /documents/credit-notes and Refunds at /documents/refunds.",
      "Both update the related invoice's status and totals.",
    ],
    notes: [
      "Using a refund where you meant a credit note makes your books show cash leaving that never left. This is the most commonly confused pair in the system, which is why it is written down.",
    ],
    next: ["doc-credit-note", "doc-refund"],
  },
  {
    id: "doc-credit-note",
    module: "documents",
    question: "How do I raise a credit note?",
    asks: ["create credit note", "cancel an invoice amount", "reduce an invoice", "write off an invoice"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/documents/credit-notes",
    steps: [
      "Open Documents then Credit Notes.",
      "Raise it against the invoice being corrected.",
      "Enter the amount and the reason. The reason is what makes this defensible at audit.",
      "The invoice's outstanding balance reduces accordingly.",
    ],
    next: ["doc-credit-vs-refund"],
  },
  {
    id: "doc-refund",
    module: "documents",
    question: "How do I refund a customer?",
    asks: ["give money back", "process a refund", "return payment", "customer wants their money back"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/documents/refunds",
    steps: [
      "Open Documents then Refunds.",
      "Raise the refund against the payment or invoice it relates to.",
      "Record the amount, the method the money is going back by, and the reason.",
      "The related documents and the finance reports update.",
    ],
    notes: [
      "Refund only what was actually received. Refunding more than was paid is possible to type and painful to unwind.",
    ],
    next: ["doc-credit-vs-refund"],
  },
  {
    id: "doc-send-whatsapp",
    module: "documents",
    question: "How do I send a document to a customer on WhatsApp?",
    asks: ["send invoice by whatsapp", "email a quote", "share a document", "send pdf to customer"],
    roles: ["ADMIN", "OPS", "FINANCE", "SALES", "MANAGER"],
    route: "/documents/invoices",
    steps: [
      "Open the document's row actions and choose to send by WhatsApp or by email.",
      "The PDF is generated with your workspace branding and attached.",
      "A row is written to the outbox before the send is attempted, so a failure is still visible.",
      "Check Communications then Outbox to confirm delivery.",
    ],
    notes: [
      "WhatsApp must be configured for the workspace, with an approved template where the provider requires one. Without it the send is queued and fails, and the outbox will show why.",
    ],
    next: ["comms-outbox", "comms-whatsapp-setup"],
  },
  {
    id: "doc-templates",
    module: "documents",
    question: "How do I change how invoices and quotations look?",
    asks: ["document template", "invoice design", "change document layout", "letterhead", "pick a template"],
    roles: ["ADMIN"],
    route: "/documents/templates",
    steps: [
      "Open Documents then Templates to see the available designs.",
      "Company name, address, contact details, tax number and logo come from Settings then Branding — not from the template.",
      "Choose the template that suits the document.",
      "Print or preview one document to check it before sending anything to a customer.",
    ],
    next: ["set-branding"],
  },
];
