import type { Procedure } from "./types";

/** Money in, money out, and the statements that explain both. */
export const FINANCE_PROCEDURES: Procedure[] = [
  {
    id: "fin-overview",
    module: "finance",
    question: "What is in the Finance area?",
    asks: ["finance module", "accounting", "where are the accounts", "financial reports list"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/finance",
    steps: [
      "Overview at /finance — the summary position.",
      "Expenses at /finance/expenses — what the business spends.",
      "Bank at /finance/bank — bank and cash accounts.",
      "Recurring at /finance/recurring — costs that repeat, like rent.",
      "Accounts at /finance/accounts — the chart of accounts.",
      "Journal at /finance/journal — manual entries.",
      "Tax Rates at /finance/tax-rates — the rates available on documents.",
      "Reports at /finance/reports — profit and loss, balance sheet, cash flow, trial balance and VAT.",
    ],
    next: ["fin-expense", "fin-reports"],
  },
  {
    id: "fin-expense",
    module: "finance",
    question: "How do I record an expense?",
    asks: ["add expense", "record a cost", "petty cash", "business spending", "log a purchase"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/finance/expenses",
    steps: [
      "Open Finance then Expenses.",
      "Add the expense with its date, amount, description, and the ledger account it belongs to.",
      "Attach the supporting document if you have one.",
      "Save. It flows into the profit and loss and the cash position.",
    ],
    notes: [
      "Category it properly. 'Miscellaneous' is where the ability to answer 'why did costs go up' goes to die.",
      "A recurring cost like rent belongs in Recurring, so it does not depend on somebody remembering each month.",
    ],
    next: ["fin-recurring", "fin-reports"],
  },
  {
    id: "fin-recurring",
    module: "finance",
    question: "How do I set up a recurring cost?",
    asks: ["recurring expense", "monthly costs", "rent and salaries", "standing costs", "repeat expense"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/finance/recurring",
    steps: [
      "Open Finance then Recurring.",
      "Add the cost with its amount and how often it repeats.",
      "It is then accounted for on schedule rather than relying on memory.",
    ],
    next: ["fin-expense"],
  },
  {
    id: "fin-bank",
    module: "finance",
    question: "How do I manage bank and cash accounts?",
    asks: ["bank accounts", "cash account", "mobile money account", "where money sits", "add a bank"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/finance/bank",
    steps: [
      "Open Finance then Bank.",
      "Add an account for each real place money sits — the till, a bank account, a mobile money wallet.",
      "Payments and expenses are recorded against these accounts.",
      "The balances are what the cash flow report is built from.",
    ],
    notes: [
      "Mirror reality. If cash and mobile money share one account here but not in life, neither balance will ever reconcile.",
    ],
    next: ["fin-reports"],
  },
  {
    id: "fin-accounts",
    module: "finance",
    question: "What is the chart of accounts and do I need to change it?",
    asks: ["chart of accounts", "account codes", "accounting categories", "ledger accounts"],
    roles: ["ADMIN", "FINANCE"],
    route: "/finance/accounts",
    steps: [
      "Open Finance then Accounts.",
      "Accounts are grouped by type — asset, liability, income, expense and equity.",
      "The default set covers an ordinary repair and retail business; most workspaces never change it.",
      "Add an account only when something genuinely does not fit an existing one.",
    ],
    notes: [
      "Adding accounts freely makes the reports harder to read, not more accurate. Fewer, well-chosen accounts beat many.",
    ],
    next: ["fin-journal"],
  },
  {
    id: "fin-journal",
    module: "finance",
    question: "How do I make a manual journal entry?",
    asks: ["journal entry", "manual accounting entry", "correct the books", "double entry", "adjustment"],
    roles: ["ADMIN", "FINANCE"],
    route: "/finance/journal",
    steps: [
      "Open Finance then Journal.",
      "Create an entry with the accounts to debit and credit. The two sides must balance.",
      "Write a narration explaining the entry. Future you will need it.",
      "Post it.",
    ],
    notes: [
      "Most corrections belong in the document that caused them — a credit note, a refund, an edited expense. A journal entry that quietly fixes a number leaves the underlying document still wrong.",
    ],
    next: ["fin-reports", "doc-credit-vs-refund"],
  },
  {
    id: "fin-reports",
    module: "finance",
    question: "Which financial report answers which question?",
    asks: ["profit and loss", "balance sheet", "cash flow", "trial balance", "VAT report", "financial statements", "am I making money"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/finance/reports",
    steps: [
      "Profit and Loss at /finance/reports/pl — did we make money over a period. Start here.",
      "Balance Sheet at /finance/reports/balance-sheet — what we own and owe at a point in time.",
      "Cash Flow at /finance/reports/cash-flow — where cash actually moved. Profit and cash are not the same thing.",
      "Trial Balance at /finance/reports/trial-balance — the accounting check that debits equal credits.",
      "VAT at /finance/reports/vat — what is due to the revenue authority.",
      "Aged Receivables — how long customers have owed you. Reached from the reports area.",
      "Set the date range deliberately. Most disagreements about a figure turn out to be two people looking at different periods.",
    ],
    notes: [
      "Profitable and out of cash is an ordinary situation: money is tied up in unpaid invoices and stock. The cash flow report and the invoice aging together explain it.",
    ],
    next: ["fin-payables", "inv-overdue"],
  },
  {
    id: "fin-payables",
    module: "finance",
    question: "How do I see what the business owes?",
    asks: ["payables", "supplier bills", "what we owe", "outstanding bills", "money going out"],
    roles: ["ADMIN", "FINANCE", "MANAGER"],
    route: "/finance",
    steps: [
      "Supplier bills and payables are reached from the Finance area.",
      "Overdue supplier bills are also surfaced on the AI Insights page.",
      "Compare payables against receivables before promising anyone money.",
    ],
    next: ["fin-reports", "inv-suppliers"],
  },
  {
    id: "fin-tax",
    module: "finance",
    question: "How do I set up tax rates?",
    asks: ["VAT rate", "tax setup", "add a tax rate", "sales tax", "tax on invoices"],
    roles: ["ADMIN", "FINANCE"],
    route: "/finance/tax-rates",
    steps: [
      "Open Finance then Tax Rates.",
      "Add each rate you charge, with its name and percentage.",
      "Rates then become selectable on quotations, invoices and sales.",
      "The tax number printed on documents comes from Settings then Branding.",
    ],
    next: ["set-branding", "fin-reports"],
  },
];
