import type { Procedure } from "./types";

/**
 * Repairs — intake through closure, including the external-technician path.
 *
 * The status list is the real one from lib/job-status.ts. There are fourteen
 * stored statuses but only eight are shown in the interface; the external-repair
 * ones fold into IN_EXTERNAL_REPAIR for display. That distinction confuses
 * people reading the database against the screen, so it is stated here once.
 */
export const JOB_PROCEDURES: Procedure[] = [
  {
    id: "job-create",
    module: "jobs",
    question: "How do I book in a new repair?",
    asks: ["create a job", "new repair", "book a device in", "log a repair", "intake a device", "add a job"],
    roles: ["ADMIN", "OPS", "FRONT_DESK", "TECH_MANAGER", "MANAGER"],
    route: "/jobs/new",
    steps: [
      "Open Jobs from the sidebar, then New Job. The direct route is /jobs/new.",
      "Enter the client. A name of at least two characters and a phone number are both required — the form will not submit without them. Email, organisation and address are optional.",
      "If the client already exists, search for them rather than retyping; a second record with the same phone splits their repair history across two files.",
      "Add the device or devices: brand, model, and the fault the client describes in their own words.",
      "Set the received date if the device came in earlier than today. Leave it alone for a walk-in happening now.",
      "Save. The job is created with status RECEIVED and is given a job number automatically, in the form ORG-YYYY-NNNN.",
      "You land on the job page. If you booked in several devices at once you land on the jobs list instead, with one job per device.",
    ],
    notes: [
      "One job is one device. A client bringing three phones gets three jobs, so each can be diagnosed, priced and collected separately.",
      "The job number is generated by the system and is unique across the workspace. Do not try to set it by hand.",
      "Intake is a four-step form — client, device, issue, review. You can go back a step without losing what you typed.",
      "The phone number matters more than it looks: it is how the client receives status messages and how the customer portal identifies them.",
    ],
    next: ["job-diagnose", "job-status-meaning"],
  },
  {
    id: "job-status-meaning",
    module: "jobs",
    question: "What do the repair statuses mean?",
    asks: ["job statuses", "what does AWAITING_APPROVAL mean", "repair stages", "status list", "what is IN_EXTERNAL_REPAIR"],
    route: "/jobs",
    steps: [
      "RECEIVED — booked in, nobody has looked at it yet.",
      "DIAGNOSING — a technician is establishing what is wrong.",
      "AWAITING_APPROVAL — the client has been quoted and has not yet said yes or no. Work should stop here until they answer.",
      "WAITING_FOR_PARTS — approved, but a part is not in stock. Check purchase orders.",
      "IN_REPAIR — actively being worked on.",
      "READY_FOR_PICKUP — finished and waiting for the client to collect.",
      "DELIVERED — handed back to the client.",
      "COMPLETED — work finished and accounted for.",
      "CLOSED — finished and archived; no further action expected.",
      "REFERRED and the external-repair statuses — the device has gone to an outside technician. See the external repair procedure.",
    ],
    notes: [
      "The database stores fourteen statuses; the interface shows eight. PENDING_EXTERNAL_ASSIGNMENT, ASSIGNED_ONE_TIME_EXTERNAL and RETURNED_FROM_EXTERNAL are all displayed as IN_EXTERNAL_REPAIR. If a report and a screen disagree, this is usually why.",
      "Changing status is what triggers client messages. A status that is corrected by editing the database directly sends nothing.",
    ],
    next: ["job-status-change", "job-external"],
  },
  {
    id: "job-status-change",
    module: "jobs",
    question: "How do I move a repair to the next stage?",
    asks: ["change job status", "update repair status", "mark job ready", "move job forward", "set status"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER", "TECHNICIAN_INTERNAL", "MANAGER"],
    route: "/jobs/[id]",
    steps: [
      "Open the job from Jobs, or search for its job number in the command palette.",
      "Change the status on the job page and save. Assign a technician from the same page, on the Overview tab.",
      "The client is messaged automatically if a communication policy is enabled for the new status, or if the fallback WhatsApp update is switched on in notification preferences.",
      "Check the job's Messages tab to confirm what was sent. It shows both outbound and inbound messages, including attempts that failed.",
    ],
    notes: [
      "A message that does not arrive is not necessarily a message that was not sent. The Messages tab shows failed attempts with their error; an empty tab means nothing was ever queued, which is a different problem.",
      "Ready-for-pickup nudges are scheduled only when configured, and are cancelled automatically if the job leaves READY_FOR_PICKUP.",
      "Every status change is recorded on the job's Audit Timeline tab, with who made it and when.",
    ],
    next: ["comms-why-no-message", "job-status-meaning"],
  },
  {
    id: "job-diagnose",
    module: "jobs",
    question: "How do I record a diagnosis and quote the client?",
    asks: ["add diagnosis", "record fault", "quote a repair", "price a job", "tell the client the cost"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER", "TECHNICIAN_INTERNAL"],
    route: "/jobs/[id]",
    steps: [
      "Open the job and record what you found and what it will take to fix.",
      "Set the price for the client. If parts are needed, add them so stock and cost are accounted for.",
      "Move the job to AWAITING_APPROVAL. This is the signal that the ball is in the client's court.",
      "The client can approve from the customer portal, or you can record their answer yourself when they phone or reply.",
      "On approval, move to IN_REPAIR — or WAITING_FOR_PARTS if something has to be ordered first.",
    ],
    notes: [
      "Jobs sitting in AWAITING_APPROVAL are the most common silent stall in the system. The AI Insights page counts them, and the invoices page has the equivalent for unpaid work.",
    ],
    next: ["job-assessment-ai", "job-parts"],
  },
  {
    id: "job-assessment-ai",
    module: "jobs",
    question: "How do I generate an assessment report for a repair?",
    asks: ["assessment report", "AI assessment", "write the report for the customer", "generate report", "technical report"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER", "TECHNICIAN_INTERNAL"],
    route: "/jobs/[id]",
    steps: [
      "Open the job. The assessment is generated from the details already on it — device, fault, diagnosis — so fill those in first.",
      "Generate the draft.",
      "Read it and edit it. The draft is a starting point, not an answer; you are the one who knows the device.",
      "Publish when you are happy with it. Only then can the client see it.",
      "The published assessment can be sent as a PDF over WhatsApp or email, and appears in the customer portal.",
    ],
    notes: [
      "The draft is never published automatically. A generated report reaches a customer only after a person has read it and chosen to publish.",
      "If report generation is unavailable, the page says so and you can write the report by hand — the workflow does not depend on it.",
    ],
    next: ["doc-send-whatsapp"],
  },
  {
    id: "job-parts",
    module: "jobs",
    question: "How do I add parts to a repair?",
    asks: ["use parts on a job", "consume stock", "add spare part", "charge parts to a repair"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER", "TECHNICIAN_INTERNAL"],
    route: "/jobs/[id]",
    steps: [
      "Open the job and add the part from the inventory list.",
      "Stock is reduced when the part is issued, and a stock transaction records who took it and for which job.",
      "If the part is not in stock, raise a purchase request rather than editing quantities by hand.",
      "Move the job to WAITING_FOR_PARTS so the delay is visible to everyone.",
    ],
    notes: [
      "Never adjust a quantity to make a job work. Every stock movement should have a reason attached to it, otherwise the valuation drifts and nobody can explain why.",
    ],
    next: ["inv-purchase-request", "inv-low-stock"],
  },
  {
    id: "job-external",
    module: "jobs",
    question: "How do I send a device to an outside technician?",
    asks: ["external technician", "refer a repair", "outsource repair", "third party repair", "send device out"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER"],
    route: "/jobs/[id]",
    steps: [
      "Open the job and refer it. The status moves through the external-repair path.",
      "Assign the external technician and record what was agreed, including their fee.",
      "While the device is out, the job shows as IN_EXTERNAL_REPAIR in the interface.",
      "When the device comes back, record the outcome and move the job on to IN_REPAIR or READY_FOR_PICKUP.",
      "The external technician's fee feeds the payouts screen under Technicians.",
    ],
    notes: [
      "An external technician signing in sees only the device and the safe diagnosis summary for jobs assigned to them. They never see the client's name, phone, email, pricing history, invoices or payments — and that is enforced by the server queries, not by hiding things on screen.",
    ],
    next: ["tech-payouts"],
  },
  {
    id: "job-find",
    module: "jobs",
    question: "How do I find a job or check its progress?",
    asks: ["search for a repair", "find a job", "where is my customer's device", "look up job number", "track a repair"],
    route: "/jobs",
    steps: [
      "Open Jobs and use the search box. It searches name, job number and phone number together.",
      "The command palette is faster if you know the job number — press the search shortcut shown in the header.",
      "Filter by status to see everything stuck at one stage, which is the usual way to work a backlog.",
      "Clients can check progress themselves in the customer portal without phoning you.",
    ],
    next: ["portal-what-client-sees"],
  },
  {
    id: "job-complete",
    module: "jobs",
    question: "How do I finish a repair and hand the device back?",
    asks: ["complete a job", "close a repair", "hand over device", "customer collecting device", "finish job"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER", "FRONT_DESK"],
    route: "/jobs/[id]",
    steps: [
      "Move the job to READY_FOR_PICKUP when the work is done. The client is notified if messaging is configured.",
      "When the client arrives, take payment. An invoice can be raised from the job so the amounts carry across.",
      "Issue a receipt once paid.",
      "Move the job to DELIVERED, then COMPLETED.",
      "CLOSED is for jobs that need no further attention and should drop out of the working lists.",
    ],
    notes: [
      "Collect payment before the device leaves. Once a device is gone, an unpaid invoice is a collections problem rather than a conversation at the counter.",
    ],
    next: ["inv-create-from-job", "pay-collect"],
  },
];
