import type { Procedure } from "./types";

/** Counter sales, clients, the sales pipeline, field service and technicians. */
export const OPERATIONS_PROCEDURES: Procedure[] = [
  {
    id: "pos-sell",
    module: "pos",
    question: "How do I sell something over the counter?",
    asks: ["point of sale", "POS", "walk-in sale", "sell a product", "counter sale", "till"],
    roles: ["ADMIN", "OPS", "SALES", "SALES_POS", "SALES_RETAIL", "FRONT_DESK", "MANAGER"],
    route: "/pos",
    steps: [
      "Open POS from the sidebar, at /pos.",
      "Add the items being bought.",
      "Take payment and record the method.",
      "Complete the sale. Stock is reduced and a receipt can be printed or sent.",
      "The sale appears in the sales list and in the finance figures.",
    ],
    notes: [
      "POS is for walk-in trade paid on the spot. If the customer is being billed to pay later, raise an invoice instead — a sale assumes the money arrived.",
    ],
    next: ["pos-history", "pay-receipt"],
  },
  {
    id: "pos-history",
    module: "pos",
    question: "How do I look up a past sale?",
    asks: ["find a sale", "sales history", "reprint a receipt", "what did we sell", "yesterday's sales"],
    route: "/pos",
    steps: [
      "Open POS. Past sales are listed with their filters.",
      "Open a sale to see its lines and payment.",
      "Reprint or resend its receipt from there.",
    ],
    next: ["pay-receipt"],
  },
  {
    id: "client-add",
    module: "clients",
    question: "How do I add or find a client?",
    asks: ["new customer", "add a client", "customer record", "find a customer", "client history"],
    roles: ["ADMIN", "OPS", "SALES", "FRONT_DESK", "MANAGER"],
    route: "/clients",
    steps: [
      "Open Clients from the sidebar.",
      "Search before adding. A duplicate splits one customer's history into two files, and nothing merges it back automatically.",
      "Add the client with name and phone at minimum; email and organisation if you have them.",
      "Open a client to see their repairs, documents and payment history in one place.",
    ],
    notes: [
      "The phone number is the identifier that matters. It is how the client receives messages and how the customer portal recognises them.",
    ],
    next: ["job-create", "portal-invite"],
  },
  {
    id: "sales-leads",
    module: "sales",
    question: "How do I track a sales lead?",
    asks: ["leads", "prospect", "sales pipeline", "follow up a customer", "opportunity", "CRM"],
    roles: ["ADMIN", "SALES", "SALES_MANAGER", "MANAGER"],
    route: "/sales/leads",
    steps: [
      "Open Sales then Leads.",
      "Add a lead with the contact and what they are interested in.",
      "Record each contact as it happens, so the next person can see where things stand.",
      "Quote the lead when they are ready; the quotation links back.",
      "Mark the outcome — won or lost, with the reason. The lost reasons are the useful half.",
    ],
    next: ["quote-create", "sales-campaigns"],
  },
  {
    id: "sales-campaigns",
    module: "sales",
    question: "How do I run a campaign to customers?",
    asks: ["campaign", "bulk message customers", "marketing", "promotion", "message all clients"],
    roles: ["ADMIN", "SALES_MANAGER", "MANAGER"],
    route: "/sales/campaigns",
    steps: [
      "Open Sales then Campaigns.",
      "Create a campaign, choose the audience and write the message. A discount code can be attached to it.",
      "Send. Messages go through the outbox, so every one is logged.",
      "Watch the outbox for failures — a bad phone number fails silently to the customer but not to you.",
    ],
    notes: [
      "Bulk sending is where messaging costs and provider limits bite. Send to a small group first and confirm delivery before sending to everyone.",
    ],
    next: ["comms-outbox"],
  },
  {
    id: "sales-targets",
    module: "sales",
    question: "How do I set sales targets?",
    asks: ["targets", "sales goals", "quota", "team target", "monthly target"],
    roles: ["ADMIN", "SALES_MANAGER", "MANAGER"],
    route: "/targets",
    steps: [
      "Open Targets at /targets.",
      "Set a target by user, department or branch.",
      "Progress is tracked against actual sales and shown on the insights pages.",
    ],
    next: ["ai-insights-read"],
  },
  {
    id: "service-field-visit",
    module: "service",
    question: "How do I schedule a field visit?",
    asks: ["field service", "site visit", "on-site repair", "book a visit", "engineer visit"],
    roles: ["ADMIN", "OPS", "TECH_MANAGER", "TECH_FIELD", "MANAGER"],
    route: "/field",
    steps: [
      "Open Field at /field, and create a visit at /field/new.",
      "Record the client, the site and what needs doing.",
      "Assign the technician and the date.",
      "The technician records the outcome after the visit; it can then be invoiced.",
    ],
    next: ["inv-issue"],
  },
  {
    id: "service-complaints",
    module: "service",
    question: "How do I handle a customer complaint?",
    asks: ["complaint", "customer unhappy", "escalation", "log a complaint", "customer issue"],
    roles: ["ADMIN", "OPS", "MANAGER"],
    route: "/complaints",
    steps: [
      "Open Complaints at /complaints.",
      "Log the complaint against the client and the job or sale it concerns.",
      "Record what was done and the outcome.",
      "Clients can also raise complaints themselves through the customer portal.",
    ],
    next: ["portal-what-client-sees"],
  },
  {
    id: "tech-payouts",
    module: "service",
    question: "How do I pay technicians for the work they have done?",
    asks: ["technician payout", "pay external technician", "technician fees", "commission", "what do we owe technicians"],
    roles: ["ADMIN", "FINANCE", "TECH_MANAGER", "MANAGER"],
    route: "/technicians",
    steps: [
      "Open Technicians from the sidebar.",
      "Payouts are calculated from the jobs each technician has completed and the fees agreed on them.",
      "Review before paying — the figures come from what was recorded on each job.",
      "Record the payout once paid.",
      "Payout follow-ups are listed at /payout-followups.",
    ],
    notes: [
      "A payout is only as accurate as the fee recorded when the job was referred. Fixing it after the fact means revisiting the job.",
    ],
    next: ["job-external"],
  },
  {
    id: "warranty-check",
    module: "service",
    question: "How do I check whether a repair is under warranty?",
    asks: ["warranty", "is this covered", "free repair", "warranty period", "repeat fault"],
    route: "/warranty",
    steps: [
      "Open Warranty at /warranty, or check the original job.",
      "The warranty terms are recorded against the completed repair.",
      "If the device is back for the same fault within the period, link the new job to the original so the history is visible.",
    ],
    next: ["job-create", "job-find"],
  },
];
