/**
 * Models with a direct `orgId` column — keep in sync with prisma/schema.prisma.
 * Used by the unified org-scoped Prisma client (`scopedDb` / `orgDb`).
 *
 * A model that HAS an orgId but is missing from this set makes scopedDb a silent
 * no-op for it: no filter injected on reads, no cross-org check on findUnique,
 * no where-clause restriction on writes. That is worse than not using the scoped
 * client at all, because the call site looks safe. Eight such models were absent
 * (the stock ledger, job photos, and the portal tables among them); nothing calls
 * the scoped client on them today, so this is defence in depth for whoever does
 * next. Any new model with an orgId column belongs here.
 */
export const ORG_SCOPED_MODELS = new Set([
  "AiFeedback",
  "AiKnowledgeArticle",
  "AiOrgSettings",
  "AiPromptLog",
  "AuditLog",
  "BankAccount",
  "BankTransaction",
  "Branch",
  "Campaign",
  "CampaignContact",
  "CashierShift",
  "ChartOfAccount",
  "Client",
  "ClientMergeRecord",
  "CommunicationPolicy",
  "CommunicationTemplate",
  "CommunicationTemplateVersion",
  "Complaint",
  "Conversation",
  "ConversationMessage",
  "CreditNote",
  "CustomerApproval",
  "CustomerConsent",
  "DeliveryNote",
  "Department",
  "Device",
  "DeviceSpecification",
  "DiagnosisReport",
  "DocumentBrandingSettings",
  "DocumentSequence",
  "DocumentTaxLine",
  "Expense",
  "FieldVisit",
  "FileAsset",
  "GoodsReceived",
  "InboundMessage",
  "InventoryCategory",
  "Invoice",
  "InvoiceAttachment",
  "InvoiceLine",
  "Job",
  "JobAssignmentHistory",
  "JobStatusHistory",
  "JournalEntry",
  "Lead",
  "Notification",
  "OrgFeatureEntitlement",
  "OrgModuleGrant",
  "OrgSubscriptionEvent",
  "OrgUsageSnapshot",
  "OutboundMessage",
  "Part",
  "PartLocationStock",
  "PartStockTransaction",
  "Payment",
  "PaymentAllocation",
  "Photo",
  "PortalUser",
  "PortalUserClient",
  "PosSession",
  "PurchaseOrder",
  "PurchaseRequest",
  "QualityCheck",
  "Quotation",
  "Receipt",
  "RecurringInvoice",
  "Refund",
  "ReorderRule",
  "RepairMessage",
  "RepairRequest",
  "RepairRequestSequence",
  "RepairTask",
  "Sale",
  "SalesTarget",
  "StockCount",
  "StockLocation",
  "StockTransfer",
  "Supplier",
  "SupplierBill",
  "SupplierPayment",
  "SupplierPrice",
  "SystemAuditEvent",
  "TaxRate",
  "TechnicianPayout",
  "User",
  "UserGroup",
  "UserInvite",
  "WarrantyClaim",
]);

/** Models with `deletedAt` — auto-filtered to active rows unless explicitly queried. */
export const SOFT_DELETE_MODELS = new Set(["FileAsset"]);
